### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Prox-y** [ThunderStorms21th/Galaxy-S10#9]
```Toolchain: default
Traceback (most recent call last):
  File "/home/fab/Desktop/Galaxy-S10/./build", line 603, in <module>
    switch_toolchain(compiler)
  File "/home/fab/Desktop/Galaxy-S10/./build", line 405, in switch_toolchain
    branch = run(['git', 'submodule', 'foreach', 'git', 'rev-parse', '--abbrev-ref', 'HEAD'],
IndexError: list index out of range```

Also the submodule command git submodule update --init --recursive says it's cloning, but it's like stuck

**Comment by ThunderStorms21th** [comment]
I've abandon online compiling and Im not inetrested to bring it back.
As You see I use only ts-build-clang-12.sh and ts-build-clang-12-aosp.sh scritp for build wich uses build python script.
So You can only compile this kernel on Your local PC/Linux/WSP machine.
